name: MinecraftPluginsHub
version: '${version}'
main: org.minecraftplugin.minecraftpluginshub.MinecraftPluginsHub
api-version: '1.20'
commands:
  test:
    description: test command
    usage: /<command>
    permission: yourplugin.yourcommandpermission
